spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true  # Использовать IP-адрес вместо имени хоста

server:
  port: 0

springdoc:
  swagger-ui:
    enabled: true
    path: /api/auth/swagger-ui.html
  api-docs:
    enabled: true
    path: /api/auth/v3/api-docs

internal:
  api-secret: ${INTERNAL_API_SECRET}

security:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${ACCESS_EXPIRATION}
    refresh-expiration: ${REFRESH_EXPIRATION}