spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: postofficemicroservice@gmail.com
    password: sjyydhuyjdolfaru  # ????????? ?????? ??????????, ? ?? ???????? ??????!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost    # ????????????? ????????? localhost
    prefer-ip-address: true  # ???????????? IP-????? ?????? ????? ?????

server:
  port: 8087

internal:
  api-secret: my-super-secret-key

resilience4j.circuitbreaker:
  instances:
    postalService:
      failureRateThreshold: 50  # ??????? Circuit Breaker ??? 50% ????????? ????????
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 2s
      minimumNumberOfCalls: 5  # ??????? 5 ??????? ????? ?????????? ?????????
      slidingWindowSize: 10  # ???? ??? ??????? ???????
      permittedNumberOfCallsInHalfOpenState: 2  # ?????????? ??????? ??? Half-Open
      waitDurationInOpenState: 10s  # ??? ????? ????? ????? ???????? ??????????????




