server:
  port: 8765

spring:
  application:
    name: gateway-api

gateway:
  routes:
    - id: auth-service
      path: /api/auth/**
      uri: lb://auth-service
    - id: postal-service
      path: /api/postal/**
      uri: lb://postal-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


