server:
  port: 8765

spring:
  application:
    name: gateway-api

gateway:
  routes:
    - id: auth-service
      path: /api/auth/**
      uri: lb://auth-service
    - id: postal-service
      path: /api/postal/**
      uri: lb://postal-service
    - id: subscriber-service
      path: /api/subscriber/**
      uri: lb://subscriber-service
    - id: publication-service
      path: /api/publication/**
      uri: lb://publication-service
    - id: subscription-service
      path: /api/subscription/**
      uri: lb://subscription-service
        
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs   # Указывает основной путь для API-документации
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true  # Убирает пустую вкладку
    urls:
      - name: Auth Service
        url: /api/auth/v3/api-docs
      - name: Postal Service
        url: /api/postal/v3/api-docs
      - name: Subscriber Service
        url: /api/subscriber/v3/api-docs
      - name: Publication Service
        url: /api/publication/v3/api-docs
      - name: Subscription Service
        url: /api/subscription/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost    # Принудительно указываем localhost
    prefer-ip-address: true  # Использовать IP-адрес вместо имени хоста


