spring:
  application:
    name: postal-service

  datasource:
    url: jdbc:postgresql://localhost:5432/po-postal
    username: postgres
    password: PosTer231
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: postal-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082