spring:
  application:
    name: subscriber-service

  datasource:
    url: jdbc:postgresql://subscriber-db:5432/${SUBSCRIBER_DB_NAME}
    username: ${SUBSCRIBER_DB_USER}
    password: ${SUBSCRIBER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: subscriber-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true  # Использовать IP-адрес вместо имени хоста

springdoc:
  swagger-ui:
    enabled: true
    path: /api/subscriber/swagger-ui.html
  api-docs:
    enabled: true
    path: /api/subscriber/v3/api-docs


server:
  port: 0

internal:
  api-secret: ${INTERNAL_API_SECRET}


security:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${ACCESS_EXPIRATION}
    refresh-expiration: ${REFRESH_EXPIRATION}

resilience4j.circuitbreaker:
  instances:
    postalService:
      failureRateThreshold: 50  # Открыть Circuit Breaker при 50% неудачных запросов
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 2s
      minimumNumberOfCalls: 5  # Минимум 5 вызовов перед изменением состояния
      slidingWindowSize: 10  # Окно для расчета отказов
      permittedNumberOfCallsInHalfOpenState: 2  # Количество попыток при Half-Open
      waitDurationInOpenState: 10s  # Как долго ждать перед попыткой восстановления


